config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, path: 'auth', controllers: { registrations: 'auth/registrations' }
  resource :magic_link, only: [:create, :show]

  resources :forms, only: [:show]
  resources :feedbacks, only: [:create]
  get 'thank_you', to: 'static_pages#form_submission'

  authenticated do
    resources :projects, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :accounts, only: [:new, :create, :index, :edit, :update, :destroy]
      resource :maintainers, only: [:edit]
      resources :maintainers, only: [] do
        resource :connection, only: [:create, :destroy], controller: 'maintainers', path: ''
      end
      resources :links, only: [:new, :create, :index, :edit, :update, :destroy]
    end
    resources :users, only: [:new, :create, :edit, :update, :index] do
      resource :admin, only: [:create, :destroy]
      resource :deactivate, only: [:destroy]
    end
    resources :forms, only: [:index] do
      member do
        post :send_form
      end
    end
    resources :feedbacks, only: [:index]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :projects_users, dependent: :destroy
  has_many :projects, through: :projects_users

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :trackable

  validates :admin, inclusion: { in: [true, false] }

  def active_for_authentication?
    super && deactivated_at.blank?
  end

  def deactivated?
    deactivated_at.present?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :load_user, only: [:edit, :update]

  def index
    authorize User
    @users = policy_scope(User).order('LOWER(first_name), LOWER(last_name)')
  end

  def new
    @user = authorize User.new(params[:user]) # The user that we need is different from the user in user_params.
  end

  def edit
  end

  def create
    @user = User.new(password: SecureRandom.alphanumeric(32))
    policy([:attributes, @user]).filter(user_params).then { @user.assign_attributes(_1) }
    @user.auto_gen_password = true

    authorize @user

    @user.skip_confirmation!

    if @user.save
      flash[:notice] = 'User created successfully!'
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages.join('. ')
      redirect_to new_user_path(user: user_params)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User edited successfully!'
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages.join('. ')
      redirect_to edit_user_path(@user)
    end
  end

  private

  def user_params
    params
      .fetch(:user, {})
      .then { policy([:attributes, @user]).filter(_1) }
      .permit(
        [:first_name, :last_name, :email]
          .then { current_user.admin? ? _1 << :admin : _1 }
      )
  end

  def load_user
    @user = authorize User.find_by(id: params[:id])
  end
end

app/views/users/_form.html.erb
<%= form_with(model: User) do |f| %>
  <div class="mb-3">
    <%= f.label :first_name, class: 'form-label required' %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :last_name, class: 'form-label required' %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :email, class: 'form-label' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :admin, class: 'form-check-label' %>
    <%= f.check_box :admin, class: 'form-check-input' %>
  </div>
  <br />
  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', root_path, class: 'btn btn-warning' %>
<% end %>

app/views/users/_header.html.erb
<div class="page-header d-print-none text-white">
  <div class="container-xl">
    <div class="row g-2 align-items-center">
      <div class="col">
        <div class="page-pretitle">
          <%= pretitle %>
        </div>
        <h2 class="page-title">
          <%= page_title %>
        </h2>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'users/header', pretitle: 'Profile settings', page_title: 'Your profile' %>
<div class="page-body">
  <div class="container-xl">
    <div class="row row-deck row-cards">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <h1><%= @user.first_name %> <%= @user.last_name %></h1>
            <br />
            <%= form_with(model: @user) do |f| %>
              <div class="mb-3">
                <%= f.label :first_name, class: 'form-label required' %>
                <%= f.text_field :first_name, class: 'form-control' %>
              </div>
              <div class="mb-3">
                <%= f.label :last_name, class: 'form-label required' %>
                <%= f.text_field :last_name, class: 'form-control' %>
              </div>
              <div class="mb-3">
                <%= f.label :email, class: 'form-label required' %>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
              <br />
              <%= f.submit 'Save', class: 'btn btn-primary' %>
              <%= link_to 'Cancel', root_path, class: 'btn btn-warning' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="page-body">
  <div class="container-xl">
    <div class="row row-cards">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Manage Admins</h3>
          </div>
          <table class="table table-striped align-middle">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Add or Remove as Admin</th>
                <th scope="col">Deactivate</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <th scope="row"><%= user.id %></th>
                  <td><%= user.first_name %> <%= user.last_name %></td>
                  <td class="py-1">
                    <% if policy([:attributes, user]).valid_admin?(false) %>
                      <%= link_to 'Remove As Admin', user_admin_path(user),
                                  method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                    <% elsif policy([:attributes, user]).valid_admin?(true) %>
                      <%= link_to 'Add As Admin', user_admin_path(user), method: :post, class: 'btn btn-success' %>
                    <% else %>
                      <%= user.admin? ? 'Admin' : 'User' %>
                    <% end %>
                  </td>
                  <td>
                    <% if user.deactivated? %>
                      Deactivated
                    <% else %>
                      <% if policy([:attributes, user]).valid_deactivated_at?(DateTime.now) %>
                        <%= link_to 'Deactivate', user_deactivate_path(user),
                                    method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %>
                      <% else %>
                        You can't deactivate this user!
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= link_to 'Back', root_path, class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="page-body">
    <div class="container-xl">
      <div class="row row-deck row-cards">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <h1>Create user</h1>
              <%= render 'form', project: @user %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mx-auto">
  <div>
    <div>
      <div>
        <%= image_tag('200.png', class: '') %>
      </div>

    </div>
    <div class="px-5">
      <div>
        <h2 class="align-middle"><%= @user.first_name %> <%= @user.last_name %></h2>
        <span>Junior Developer</span>
        <div class="mt-3">
          <%= button_tag(type: 'submit', class: 'px-4') do %>
            <i></i> Send message
          <% end %>
        </div>
      </div>

      <div class="py-4">
        <h4>Info</h4>
        <table>
          <tbody>
            <tr>
              <td>E-mail:</td>
              <td><%= mail_to @user.email, @user.email %></td>
            </tr>
            <tr>
              <td>Phone:</td>
              <td>+36/30 123 1234</td>
            </tr>
          </tbody>

        </table>
      </div>

      <div>
        <h4>Attached projects</h4>
        <% if @user.projects.any? %>

        <% @user.projects.each do |project| %>
         <%= link_to project.title, project %>
        <% end %>
          <% else %>
        This user isn't attached to any projects yet.
        <% end %>
      </div>

      <% if current_user == @user %>
        <%= link_to 'Edit profile', edit_user_registration_path %>
      <% end %>
    </div>
  </div>
</div>