config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, path: 'auth', controllers: { registrations: 'auth/registrations' }
  resource :magic_link, only: [:create, :show]

  resources :forms, only: [:show]
  resources :feedbacks, only: [:create]
  get 'thank_you', to: 'static_pages#form_submission'

  authenticated do
    resources :projects, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :accounts, only: [:new, :create, :index, :edit, :update, :destroy]
      resource :maintainers, only: [:edit]
      resources :maintainers, only: [] do
        resource :connection, only: [:create, :destroy], controller: 'maintainers', path: ''
      end
      resources :links, only: [:new, :create, :index, :edit, :update, :destroy]
    end
    resources :users, only: [:new, :create, :edit, :update, :index] do
      resource :admin, only: [:create, :destroy]
      resource :deactivate, only: [:destroy]
    end
    resources :forms, only: [:index] do
      member do
        post :send_form
      end
    end
    resources :feedbacks, only: [:index]
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @projects = if params[:all] == 'true'
                  policy_scope(Project)
                else
                  policy_scope(current_user.projects)
                end
                  .order(Arel.sql('projects.deactivated_at IS NULL DESC'))
  end
end

app/views/home/index.html.erb
<div class="page-header d-print-none text-white">
  <div class="container-xl">
    <div class="row g-2 align-items-center">
      <div class="col">
        <div class="page-pretitle">
          Overview
        </div>
        <h2 class="page-title">
          Projects
        </h2>
      </div>
      <div class="col-auto ms-auto d-print-none">
        <div class="btn-list">
          <% if params[:all] == 'true' %>
            <%= link_to root_path(all: 'false'), class: 'btn btn-primary' do %>
              <%= inline_svg_pack_tag('static/node_modules/@tabler/icons/icons/eye.svg') %>
              View my projects
            <% end %>
          <% else %>
            <%= link_to root_path(all: 'true'), class: 'btn btn-primary' do %>
              <%= inline_svg_pack_tag('static/node_modules/@tabler/icons/icons/eye.svg') %>
              View all projects
            <% end %>
          <% end %>
          <%= link_to new_project_path, class: 'btn btn-primary d-none d-sm-inline-block' do %>
            <%= inline_svg_pack_tag('static/node_modules/@tabler/icons/icons/plus.svg') %>
            Create new project
          <% end %>

          <%= link_to new_user_path, class: 'btn btn-primary d-none d-sm-inline-block' do %>
            <%= inline_svg_pack_tag('static/node_modules/@tabler/icons/icons/plus.svg') %>
            Create new user
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>
<div class="container mx-auto">
  <% if !@projects.nil? %>
    <div>
      <div class="page-body">
        <div class="container-xl">
          <div class="row row-deck row-cards">
            <% @projects.each do |project| %>
              <%= render 'projects/project', project: project %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <p>No projects could be found.</p>
  <% end %>
</div>