config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, path: 'auth', controllers: { registrations: 'auth/registrations' }
  resource :magic_link, only: [:create, :show]

  resources :forms, only: [:show]
  resources :feedbacks, only: [:create]
  get 'thank_you', to: 'static_pages#form_submission'

  authenticated do
    resources :projects, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :accounts, only: [:new, :create, :index, :edit, :update, :destroy]
      resource :maintainers, only: [:edit]
      resources :maintainers, only: [] do
        resource :connection, only: [:create, :destroy], controller: 'maintainers', path: ''
      end
      resources :links, only: [:new, :create, :index, :edit, :update, :destroy]
    end
    resources :users, only: [:new, :create, :edit, :update, :index] do
      resource :admin, only: [:create, :destroy]
      resource :deactivate, only: [:destroy]
    end
    resources :forms, only: [:index] do
      member do
        post :send_form
      end
    end
    resources :feedbacks, only: [:index]
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :projects_users, dependent: :destroy
  has_many :maintainers, class_name: 'User', foreign_key: 'user_id', through: :projects_users

  has_many :accounts, dependent: :destroy
  has_many :links, dependent: :destroy
  has_many :forms, dependent: :destroy

  validates :title, presence: true
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :load_project, only: [:show, :edit, :update, :destroy]

  def show
    @links = policy_scope(@project.links).order(updated_at: :desc).first(10)
  end

  def new
    @project = authorize Project.new(project_params)
  end

  def edit
  end

  def create
    @project = authorize current_user.projects.build(project_params)
    @project.maintainers << current_user

    if @project.save
      flash[:notice] = 'Project created successfully!'
      redirect_to root_path
    else
      flash[:alert] = @project.errors.full_messages.join('. ')
      redirect_to new_project_path(project: project_params)
    end
  end

  def update
    if @project.update(project_params)
      flash[:notice] = 'Project updated successfully!'
      redirect_to project_path(@project)
    else
      flash[:alert] = @project.errors.full_messages.join('. ')
      redirect_to edit_project_path
    end
  end

  def destroy
    if @project.update(deactivated_at: DateTime.now)
      flash[:notice] = 'Project deactivated successfully!'
      redirect_to root_path
    else
      flash[:alert] = 'This project cannot be deactivated.'
      redirect_to project_path(@project)
    end
  end

  private

  def project_params
    params
      .fetch(:project, {})
      .then { policy([:attributes, :project]).filter(_1) }
      .permit(
        [:title]
          .then { current_user.admin? ? _1 << :deactivated_at : _1 }
      )
  end

  def load_project
    @project = authorize Project.find_by(id: params[:id])
  end
end

app/views/projects/_counter_overview.html.erb
<div class="card card-sm">
  <div class="card-body">
    <div class="row align-items-center">
      <div class="col-auto">
        <span class="bg-muted text-white avatar">
          <%= inline_svg_pack_tag(icon_path) %>
        </span>
      </div>
      <div class="col">
        <div class="font-weight-medium">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<div class="page-body">
  <div class="container-xl">
    <div class="row row-deck row-cards">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <br />
            <%= form_with(model: project) do |f| %>
              <div class="mb-3">
                <%= f.label :title, class: 'form-label required' %>
                <%= f.text_field :title, class: 'form-control' %>
              </div>
              <br />
              <%= f.submit 'Save', class: 'btn btn-primary' %>
              <%= link_to 'Cancel', root_path, class: 'btn btn-warning' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_header.html.erb
<div class="page-header d-print-none text-white">
  <div class="container-xl">
    <div class="row g-2 align-items-center">
      <div class="col">
        <div class="page-pretitle">
          Project overview
        </div>
        <h2 class="page-title">
          <%= link_to project.title, project_path(project) %>
        </h2>
      </div>
      <div class="col-auto ms-auto d-print-none">
        <div class="btn-list">
          <span class="dropdown">
            <a href="#" class="btn btn-primary dropdown-toggle align-text-top show"
               data-bs-boundary="viewport" data-bs-toggle="dropdown">
                <%= inline_svg_pack_tag('static/node_modules/@tabler/icons/icons/plus.svg') %> New
            </a>
            <div class="dropdown-menu dropdown-menu-end" data-popper-placement="bottom-end" style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate3d(0px, 29.5px, 0px);">
              <%= link_to 'Account', new_project_account_path(project), class: 'dropdown-item' %>
              <%= link_to 'Link', new_project_link_path(project), class: 'dropdown-item' %>
            </div>
          </span>
        </div>
      </div>
      <% if policy(project).edit? %>
        <div class="col-auto ms-auto d-print-none">
          <%= link_to edit_project_path(project), class: 'btn btn-primary' do %>
              <%= inline_svg_pack_tag('static/node_modules/@tabler/icons/icons/pencil.svg') %> Edit
          <% end %>
        </div>
      <% end %>
      <% form = project.forms.last %>
      <% if form.present? && policy(:feedback).index? %>
        <div class="col-auto ms-auto d-print-none">
          <%= link_to feedbacks_path(feedback: { form_id: form.id }), class: 'btn btn-primary' do %>
            <%= inline_svg_pack_tag('static/node_modules/@tabler/icons/icons/users.svg') %> Feedbacks
          <% end %>
        </div>
      <% end %>
      <% if policy(@project).destroy? %>
        <div class="col-auto ms-auto d-print-none">
          <% if project.deactivated_at.blank? %>
            <%= link_to project_path(project),
                        method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
              <span class="d-md-flex d-lg-inline-block align-middle">
                <%= inline_svg_pack_tag('static/node_modules/@tabler/icons/icons/trash.svg', class: 'm-0') %> Delete
              </span>
            <% end %>
          <% else %>
            <%= link_to project_path(project, { project: { deactivated_at: nil } }),
                        method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
              <span class="d-md-flex d-lg-inline-block align-middle">
                <%= inline_svg_pack_tag('static/node_modules/@tabler/icons/icons/eye.svg', class: 'm-0') %> Reactivate
              </span>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/_project.html.erb
<div class="col-12">
  <div class="card<%= project.deactivated_at.present? ? ' theme-dark' : '' %>">
    <div class="card-header">
      <h3 class="card-title">
        <%= link_to project.title, project, class: 'link-secondary' %>
      </h3>
    </div>
    <div class="card-body">
      <div class="datagrid">
        <div class="datagrid-item">
          <div class="datagrid-title">Maintainers</div>
          <div class="datagrid-content">
            <div class="avatar-list avatar-list-stacked">
              <% project.maintainers.each do |maintainer| %>
                <span class="avatar avatar-xs avatar-rounded">
                  <%= maintainer.first_name.first %><%= maintainer.last_name.first %>
                </span>
              <% end %>
            </div>
          </div>
        </div>
        <div class="datagrid-item">
          <div class="datagrid-title">Accounts</div>
          <div class="datagrid-content">
            <%= link_to project.accounts.count, project, class: 'link-secondary' %>
          </div>
        </div>
        <div class="datagrid-item">
          <div class="datagrid-title">Last updated</div>
          <div class="datagrid-content">
            <%= (Time.zone.today - project.updated_at.to_date).to_i %> days ago
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="page-body">
    <div class="container-xl">
      <div class="row row-deck row-cards">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <h1>Edit <strong><%= @project.title %></strong></h1>
              <%= render 'form', project: @project %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="page-body">
    <div class="container-xl">
      <div class="row row-deck row-cards">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <h1>Create project</h1>
              <%= render 'form', project: @project %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<%= render 'projects/header', project: @project %>
<div class="page-body">
  <div class="container-xl">
    <div class="row row-cards">
      <div class="col-sm-6 col-lg-3">
        <%= render 'projects/counter_overview', icon_path: 'static/node_modules/@tabler/icons/icons/key.svg' do %>
          <%= link_to "#{@project.accounts.count} #{'Account'.pluralize(@project.accounts.count)}",
                      project_accounts_path(@project) %>
        <% end %>
      </div>
      <div class="col-sm-6 col-lg-3">
        <%= render 'projects/counter_overview', icon_path: 'static/node_modules/@tabler/icons/icons/users.svg' do %>
          <%= link_to "#{@project.maintainers.count} #{'Maintainer'.pluralize(@project.maintainers.count)}",
                      edit_project_maintainers_path(@project) %>
        <% end %>
      </div>
      <div class="col-sm-6 col-lg-3">
        <%= render 'projects/counter_overview', icon_path: 'static/node_modules/@tabler/icons/icons/link.svg' do %>
          <%= link_to "#{@project.links.count} #{'Link'.pluralize(@project.links.count)}",
                      project_links_path(@project) %>
        <% end %>
      </div>
    </div>
    <div class="row row-cards mt-2">
      <%= render 'links/table', links: @links, action_buttons: false %>
    </div>
  </div>
</div>