config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, path: 'auth', controllers: { registrations: 'auth/registrations' }
  resource :magic_link, only: [:create, :show]

  resources :forms, only: [:show]
  resources :feedbacks, only: [:create]
  get 'thank_you', to: 'static_pages#form_submission'

  authenticated do
    resources :projects, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :accounts, only: [:new, :create, :index, :edit, :update, :destroy]
      resource :maintainers, only: [:edit]
      resources :maintainers, only: [] do
        resource :connection, only: [:create, :destroy], controller: 'maintainers', path: ''
      end
      resources :links, only: [:new, :create, :index, :edit, :update, :destroy]
    end
    resources :users, only: [:new, :create, :edit, :update, :index] do
      resource :admin, only: [:create, :destroy]
      resource :deactivate, only: [:destroy]
    end
    resources :forms, only: [:index] do
      member do
        post :send_form
      end
    end
    resources :feedbacks, only: [:index]
  end
end

app/controllers/forms_controller.rb
# frozen_string_literal: true

class FormsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :load_form, only: [:send_form]

  def index
    @forms = policy_scope(Form)
  end

  def show
    @form = Form.find_by(id: params[:id])

    # Accessible by users who are not logged in
    skip_authorization
    raise Pundit::NotAuthorizedError if @form.secret != params[:secret]

    @questions = [
      @form.string_questions.to_a,
      @form.text_questions.to_a,
      @form.select_questions.to_a,
      @form.scale_questions.to_a
    ].flatten.sort_by(&:order)
  end

  def send_form
    @form.project.maintainers
      .where(users: { admin: false })
      .find_each do |user|
        FormMailer.with(user: user, form: @form).send_form.deliver
      end
    flash[:notice] = 'Form sent to Maintainers!'
    redirect_to forms_path
  end

  private

  def load_form
    @form = authorize Form.find_by(id: params[:id])
  end
end

app/views/forms/_scale_question.html.erb
<div class="mb-3">
  <%= f.fields_for :scale_answers_attributes, index: nil do |nf| %>
    <% id = "feedback_scale_answers_attributes_#{question.id}_answer" %>
    <%= nf.label :answer, question.question, class: 'form-label', for: id %>
    <%= nf.range_field :answer, class: 'form-range', id: id, min: question.minimum, max: question.maximum, step: 1 %>
    <%= nf.hidden_field :scale_question_id, value: question.id %>
  <% end %>
</div>

app/views/forms/_select_question.html.erb
<div class="mb-3">
  <%= f.fields_for :select_answers_attributes, index: nil do |nf| %>
    <% id = "feedback_select_answers_attributes_#{question.id}_answer" %>
    <%= nf.label :answer, question.question, class: 'form-label', for: id %>
    <%= nf.select :answer, question.options, { include_blank: true }, class: 'form-select', id: id %>
    <%= nf.hidden_field :select_question_id, value: question.id %>
  <% end %>
</div>

app/views/forms/_string_question.html.erb
<div class="mb-3">
  <%= f.fields_for :string_answers_attributes, index: nil do |nf| %>
    <% id = "feedback_string_answers_attributes_#{question.id}_answer" %>
    <%= nf.label :answer, question.question, class: 'form-label', for: id %>
    <%= nf.text_field :answer, class: 'form-control', id: id %>
    <%= nf.hidden_field :string_question_id, value: question.id %>
  <% end %>
</div>

app/views/forms/_text_question.html.erb
<div class="mb-3">
  <%= f.fields_for :text_answers_attributes, index: nil do |nf| %>
    <% id = "feedback_text_answers_attributes_#{question.id}_answer" %>
    <%= nf.label :answer, question.question, class: 'form-label', for: id %>
    <%= nf.text_area :answer, class: 'form-control', id: id %>
    <%= nf.hidden_field :text_question_id, value: question.id %>
  <% end %>
</div>

app/views/forms/index.html.erb
<div class="container mx-auto">
  <div class="page-body">
    <div class="container-xl">
      <h1 class="text-center text-white">Forms</h1>
      <div class="row row-deck row-cards">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <table class="table">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Send Form</th>
                  </tr>
                </thead>
                <tbody>
                  <% @forms.each do |form| %>
                    <tr>
                      <td><%= link_to form.title, feedbacks_path(feedback: { form_id: form.id }) %></td>
                      <td><%= form.description %></td>
                      <td>
                        <%= link_to 'Send', send_form_form_path(form),
                                    method: :post,
                                    data: { confirm: 'Are you sure you want to send this form via email to all non-admin maintainers?' },
                                    class: 'btn btn-primary' %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <% if @forms.blank? %>
                <p>No forms could be found.</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/forms/show.html.erb
<div class="page-body">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="container container-tight py-4">
          <div class="card card-md">
            <div class="card-body">
              <p class="fw-bold fs-3"><%= @form.title %></p>
              <% if @form.description.present? %>
                <p><%= @form.description %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="container container-tight py-4">
          <div class="card card-md">
            <div class="card-body">
              <%= form_with model: Feedback, url: feedbacks_path(secret: params[:secret]), method: :post do |f| %>
                <%= f.hidden_field :form_id, value: @form.id %>
                <% @questions.each do |question| %>
                  <%= render question.class.to_s.underscore, question: question, f: f %>
                <% end %>
                <%= f.submit 'Submit', class: 'btn btn-primary' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>